### ISSUE TITLE
need a one liner to setup aws cli for localstack

### ISSUE THREAD

**Issue by bjm88** [localstack/awscli-local#10]
Hi - we are setting up localstack in our CircleCI CI/CD env for auto testing...and its been a big pain...
now we need to install python (didnt before) to just install aws cli (didn't before) to just be able to setup a default SQS queue......(vs env var or http post to do it)

our unit test build now taking a long time, and we can't seem to actually get aws cli to just setup via aws configure in one line with NO prompting interactively (we set all aws env vars ahead of time...)

please help (realize it not specifically the job of this wrapper, but not sure where else to post...)

**Comment by whummer** [comment]
Thanks for reporting @bjm88 

> now we need to install python (didnt before) to just install aws cli (didn't before) to just be able to setup a default SQS queue......(vs env var or http post to do it)

Installing python and the `aws` CLI is not strictly required - you should be able to use LocalStack with any other AWS SDK as well (e.g., AWS SDK for Java, Node.js, ...). Just make sure that the endpoint URL are configured to point to the correct URLs on `localhost`.

It would be helpful if you could provide a more detailed error report, including the exact commands you're running, and the detailed error logs. Thanks

**Comment by bjm88** [comment]
We worked around it, but thanks for following up.  I was basically asking for a one liner in that we want to start localstack and tell it to initialize a queue, doesn't seem possible, but we worked it out after the fact with dependency startup management in docker-compose and some polling scripts.
