### ISSUE TITLE
This doesn't work at all for Windows

### ISSUE THREAD

**Issue by aggieben** [localstack/awscli-local#11]
In Windows 10, when I run `awslocal`, the Windows Shell prompts me to open the awslocal script instead of executing it.

**Comment by jmb12686** [comment]
Same here, looks like on Windows, there is no `awslocal.cmd` or `awslocal.exe` installed in the Python3X\Scripts\ directory.  Instead, there is just an extension-less `awslocal` file, that appears to be a py file?

**Comment by whummer** [comment]
Thanks for reporting @aggieben @jmb12686 . This should be fixed in 8878701 . Can you please give it a try with the latest version 0.5 of the pip package? Please report here if the problem persists. Thanks
