### ISSUE TITLE
Testing issue when trying to add to conda-forge

### ISSUE THREAD

**Issue by mwilson8** [localstack/awscli-local#12]
I'm attempting to add this to conda-forge and in the recipe have the command ```awslocal -h``` to simply check for functionality, which runs fine on linux & mac osx but when testing in azure on windows I get "awslocal is not recognized as an internal or external command"
Is there a different command I can use to test that installation was successful?

**Comment by whummer** [comment]
Thanks for reporting @mwilson8 . Looks like a duplicate of #11 - we'll push a fix shortly.

**Comment by whummer** [comment]
This should be fixed in 8878701 . Can you please give it a try with the latest version 0.5 of the pip package? Please report here if the problem persists. Thanks

**Comment by mwilson8** [comment]
Successful build in https://github.com/conda-forge/awscli-local-feedstock/pull/2. Thanks!
