### ISSUE TITLE
Issue running any awslocal command on Windows 10

### ISSUE THREAD

**Issue by ghost** [localstack/awscli-local#15]
![image](https://user-images.githubusercontent.com/44377377/74278803-ca18ca00-4ce7-11ea-859a-a74481fd944f.png)
This is the response for any `awslocal` command.

**Comment by skergetd** [comment]
Same here. Had no chance to solve it so far...any ideas?

**Comment by whummer** [comment]
Thanks for reporting @mgrantsmarsh @skergetd . We've pushed a new version that should hopefully fix this issue. Can you please do a `pip install --upgrade --no-cache 'awscli-local>=0.6'` and give it another try? Thanks

**Comment by wtsiamruk** [comment]
Hi all, I'm also having issues using the tool, would like to give you more information but I see only error code in my case

![image](https://user-images.githubusercontent.com/20062612/81115621-b074d080-8f2c-11ea-9539-44eef1a42954.png)

**Comment by 4lex1v** [comment]
Bat script on windows needs to turn echoing off, example:

```
@echo off
python %~dp0\awslocal %*
```

**Comment by whummer** [comment]
Thanks @4lex1v - can you please elaborate why this is required? Closing this issue, as we haven't heard about this issue in a while. If the issue persists, please feel free to open a pull request.. Thanks for your help!
