### ISSUE TITLE
awslocal s3api on windows 10

### ISSUE THREAD

**Issue by navforu** [localstack/awscli-local#16]
Trying to provide public read to the bucket: bucket "tutorial" created.
running the following command - 
awslocal s3api put-bucket-acl --bucket tutorial --acl public-read
returns -
>usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
>To see help text, you can run:

>aws help
>aws <command> help
>aws <command> <subcommand> help
>aws: error: the following arguments are required: --bucket*

--bucket is provided in the command.

**Comment by whummer** [comment]
Thanks for reporting @navforu . I wasn't able to reproduce this issue - the command you posted seems to be working for me. Can you please post the output of `aws --version`, and potentially try upgrading to the latest version: `pip install --upgrade --no-cache awscli`. Thanks

**Comment by whummer** [comment]
Thanks for reporting @navforu . I wasn't able to reproduce this issue - the command you posted seems to be working for me. Can you please post the output of `aws --version`, and potentially try upgrading to the latest version: `pip install --upgrade --no-cache awscli`. Thanks

**Comment by whummer** [comment]
Quick update @navforu : We've pushed a new version that should potentially fix your issue. Can you please do a `pip install --upgrade --no-cache 'awscli-local>=0.6'` and give it another try? Thanks

**Comment by navforu** [comment]
> 
> 
> Thanks for reporting @navforu . I wasn't able to reproduce this issue - the command you posted seems to be working for me. Can you please post the output of `aws --version`, and potentially try upgrading to the latest version: `pip install --upgrade --no-cache awscli`. Thanks

I got the notification after you closed the issue. Thanks for your reply, we end up not using it at this time. Will get back some time check if the upgraded code works.
