### ISSUE TITLE
awslocal cli-read-timeout doesn't work as expected

### ISSUE THREAD

**Issue by svoychik** [localstack/awscli-local#18]
Trying to add read-timeout to my awslocal command but it doesn't help:
_awslocal sqs list-queues --cli-read-timeout 5_
connect timeout doesn't work as well:
_awslocal sqs list-queues --cli-connect-timeout 5_
 

**OS: Windows 10** 
**awslocal --v**: aws-cli/1.18.39 Python/2.7.17 Windows/10 botocore/1.15.39

**Comment by lakkeger** [comment]
Hi! We just wanted to follow up to see whether your issue has been resolved. Were you able to get it working with the latest version of LocalStack? We would appreciate your feedback!

**Comment by lakkeger** [comment]
Closing the above issue due to inactivity.
