### ISSUE TITLE
port mapping

### ISSUE THREAD

**Issue by jl-DaDar** [localstack/awscli-local#19]
in docker compose we remapped localstack ports to other port, and because of this awslocal cannot connect to the services properly. Is there anyway we can also remap awscli ports? thanks!

**Comment by whummer** [comment]
Thanks for reporting @jl-DaDar . Please note that all services are now accessible via the edge port (and the individual service ports are deprecated). Please follow this item for work on configuring the edge port for the `awslocal` CLI: https://github.com/localstack/awscli-local/issues/23 Thanks
