### ISSUE TITLE
Support for EDGE_PORT

### ISSUE THREAD

**Issue by ngander-amfam** [localstack/awscli-local#23]
It appears that `awslocal` doesn't support the new edge port (4566). Can support for this be added as it appears the service specific ports are deprecated and will soon disappear? Also, it would be nice if custom edge ports (as per the container EDGE_PORT environment variable) were supported, too.

**Comment by chenavazer** [comment]
with EDGE_PORT `awslocal` is less interesting

**Comment by macnev2013** [comment]
Hey @ngander-amfam , Thanks for feedback. Can you give it a try after updating `awscli-local` to the `latest` version for edge port support. Also we have support for custom edge ports - you can export the variable `EDGE_PORT` using `export EDGE_PORT=XXXX` for customising the edge port.
Thanks.
