### ISSUE TITLE
Feature request: Set AWS_DEFAULT_REGION to DEFAULT_REGION from LocalStack

### ISSUE THREAD

**Issue by philBrown** [localstack/awscli-local#24]
The LocalStack [Configuration](https://github.com/localstack/localstack#configurations) specifies a `DEFAULT_REGION` environment variable.

It would be great if `awslocal` could use this when it is set so that when running in the LocalStack container it doesn't automatically use `us-east-1` if `DEFAULT_REGION` has been configured differently.

**Comment by whummer** [comment]
Thanks @philBrown - this has been added in #27 . A new version `0.9` has been released. Please let us know if there are any issues. Thanks
