### ISSUE TITLE
awslocal sqs list-queues doesn't work

### ISSUE THREAD

**Issue by alejandroandreu** [localstack/awscli-local#25]
Listing SQS queues doesn't work with `awslocal` but it does work with plain `aws` pointing it to the right port.

```
$ AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar AWS_DEFAULT_REGION=eu-west-3 aws --endpoint-url=http://localhost:4566 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/queue1-dead-letter",
        "http://localhost:4566/000000000000/queue2-dead-letter",
        "http://localhost:4566/000000000000/queue2",
        "http://localhost:4566/000000000000/queue1"
    ]
}
$ awslocal sqs list-queues
$
```

**Comment by alejandroandreu** [comment]
Sending a message to these queues with `awslocal` doesn't seem to work either. I'm getting the following output:

```
An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the SendMessage operation: The specified queue does not exist for this wsdl version.
```

Which works with plain `aws`. I'm assuming the whole suite of SQS commands are broken.

**Comment by whummer** [comment]
Thanks for reporting @alejandroandreu . Can you please try running the command with region specified:
```
$ AWS_DEFAULT_REGION=eu-west-3 awslocal sqs list-queues
```

Also, which version of the CLI are you using?
```
$ awslocal --version
$ aws --version
```
Thanks

**Comment by whummer** [comment]
Unable to reproduce this issue with the details provided. Please report here or open a follow-up issue if the problem persists. Thanks
