### ISSUE TITLE
All versions of awscli-local now use localstack's single edge service (introduced in v 0.11.0)

### ISSUE THREAD

**Issue by longbowrocks** [localstack/awscli-local#26]
The versions in requirements.txt are unlocked, so all versions of awscli-local now try to use the edge service.

Example of problem:
`$> pip install awscli-local==0.4`
`$> docker run -d -p 4566-4583:4566-4583 localstack/localstack:0.10.7`
`$> awslocal s3 ls`
`An error occurred (404) when calling the ListBuckets operation: Not Found`

Better example, don't run localstack:
`$> pip install awscli-local==0.4`
`$> awslocal s3 ls`
`Could not connect to the endpoint URL: "http://localhost:4566/"`

**Comment by onlyabhi52** [comment]
The same problem is being faced at our end too with the localstack latest version.

**Comment by whummer** [comment]
Thanks for reporting @longbowrocks @onlyabhi52 . Can you please try setting the `USE_LEGACY_PORTS=1` environment variable in your terminal.

Alternatively, you can try downgrading the `localstack-client` pip package:
```
pip install 'localstack-client==1.2'
```
Hope that helps - please keep us posted. Thanks

**Comment by longbowrocks** [comment]
Downgrading the client manually works.

I ended up upgrading localstack instead because someone replaced the elasticsearch version in localstack 0.10.7 with elasticsearch 7.x.

**Comment by elish214** [comment]
@whummer @longbowrocks 
we were facing the same issue.
using localstack 0.11.4v
i tried to downgrade "localstack-client==1.2" like **_whummer_** said and it worked, thanks

**Comment by whummer** [comment]
Thanks @elish214 , glad you were able to get it working. The connection issue from Lambda sounds like a different problem. Can you please try using the `LOCALSTACK_HOSTNAME` environment variable (see README in main repo for details). Please open an issue with detailed steps to reproduce if the problem persists. Thanks
