### ISSUE TITLE
Bug during cloudformation deploy -- Unknown options: --s3-endpoint-url

### ISSUE THREAD

**Issue by carlschroedl** [localstack/awscli-local#34]
# Observed Behavior
```bash
$> awslocal cloudformation deploy --template-file template.yml --stack-name throwaway

Unknown options: --s3-endpoint-url=http://localhost:4566
```
Exit code `252`

# Expected Behavior

```bash
$> awslocal cloudformation deploy --template-file template.yml --stack-name throwaway
```
(command succeeds with exit code `0`)

# Details

```bash
$> pip3 show awscli-local
Name: awscli-local
Version: 0.13
Summary: Thin wrapper around the "aws" command line interface for use with LocalStack
Home-page: https://github.com/localstack/awscli-local
Author: Waldemar Hummer
Author-email: waldemar.hummer@gmail.com
License: Apache License 2.0
Location: /home/carlschroedl/.local/lib/python3.6/site-packages
Requires: localstack-client
$> aws --version
aws-cli/2.1.17 Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.18 prompt/off
$> localstack --version
/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.3) or chardet (3.0.4) doesn't match a supported version!
0.12.6.1
```

I also tried specifying my own value for `--s3-endpoint-url`. This failed with different output.

```bash
$> awslocal cloudformation deploy --s3-endpoint-url http://localhost:4566 --template-file template.yml --stack-name throwaway

Unknown options: --s3-endpoint-url=http://localhost:4566,--s3-endpoint-url,http://localhost:4566
```
Exit code `252`

**Comment by carlschroedl** [comment]
Potential workaround: downgrade to AWS CLI v1

After uninstalling AWS CLI v2, and installing AWS CLI v1 via pip, the command gets much farther.

```bash
$> aws --version
aws-cli/1.19.7 Python/3.6.9 Linux/5.4.0-58-generic botocore/1.20.7
$> awslocal cloudformation deploy --template-file simple-template.yml --stack-name blah

Waiting for changeset to be created..
Waiting for stack create/update to complete
```

It appears to be hung; a cloudformation template containing only an S3 bucket does not complete within ~3 minutes. No output is logged in localstack launched via `SERVICES=cloudfront,serverless localstack start` This may be a localstack problem rather than an awscli-local problem.

**Comment by paul-uz** [comment]
@carlschroedl I did was suggested and installed aws v1 and linked it, but I still get the error `Unknown options: --s3-endpoint-url=http://localhost:4566,--s3-endpoint-url,http://localhost:4566`

**Comment by rnjailamba** [comment]
We removed the python packages and reinstalled by `pip3 install awscli-local[ver1]` and` pip3 install --upgrade awscli` and the above problems went away. Python3 may be an issue @paul-uz. This can be closed @whummer .
