### ISSUE TITLE
Can I replace this script with a bash alias ?

### ISSUE THREAD

**Issue by GromNaN** [localstack/awscli-local#35]
The [first example in the readme](https://github.com/localstack/awscli-local#example) shows that the `localaws` is a shortcut for `aws --endpoint-url=http://localhost:4566`. After digging in the code, I found the following bash alias could replace this python script.

```shell
alias localaws="AWS_ACCESS_KEY_ID=_not_needed_locally_ AWS_SECRET_ACCESS_KEY=_not_needed_locally_ AWS_DEFAULT_REGION=${DEFAULT_REGION:-$AWS_DEFAULT_REGION}} aws --endpoint-url=http://${LOCALSTACK_HOST:-localhost}:4566"
```
Is there anything that the python script does, that would fail with this alias ?

Don't get me wrong. I understand this script was necessary when each service was exposed on a distinct port ; and it might be necessary for Windows. I'm trying to minimize my dependencies.

Perhaps, this alternative could be documented ; if it's correct.

**Comment by whummer** [comment]
Thanks for reporting this @GromNaN . Great idea - this alias would probably cover 99% of the use cases.

I'd slightly change to (adapting the credentials):
```
alias localaws="AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=${DEFAULT_REGION:-$AWS_DEFAULT_REGION}} aws --endpoint-url=http://${LOCALSTACK_HOST:-localhost}:4566"
```

There's only one thing - this will likely not support the `localaws cloudformation package ...` command, as this command requires an additional `--s3-endpoint-url` command line parameter. 

Would be great if you could add this alias to the README - happy to accept a pull request! Thanks
