### ISSUE TITLE
[Feature Request] Setting for changing localstack port

### ISSUE THREAD

**Issue by rostanin** [localstack/awscli-local#37]
Currently, it is only possible to change the localstack host by setting LOCALSTACK_HOST.
Sometimes it is also required to change the default port. Can it be added?

**Comment by whummer** [comment]
Thanks for reporting @rostanin . You can customize the port number by setting the `EDGE_PORT` environment variable.

This CLI library uses the `localstack-client` Python module under the covers, which provides this configuration here: https://github.com/localstack/localstack-python-client/blob/master/localstack_client/config.py#L5-L6

Please let us know if there are any issues. Thanks!
