### ISSUE TITLE
No such file or directory if user name has spaces in windows

### ISSUE THREAD

**Issue by stevenpila** [localstack/awscli-local#38]
Hi,

When we to try to run the command below, we get no such file or directory.
![image](https://user-images.githubusercontent.com/6943024/109480632-b7ba2b80-7ab6-11eb-8862-ac11dacfde1d.png)
It seems there's no handling if user name has spaces.

We tried to find solutions but failed. Can anyone help us with this one? 

Thanks.

**Comment by whummer** [comment]
Thanks for reporting this issue @stevenpila . Can you please install the latest version and give it another try:
```
pip install --upgrade --no-cache awscli-local
```
Please keep us posted how it goes. Thanks
