### ISSUE TITLE
Unable to use awslocal - no module named localstack-client

### ISSUE THREAD

**Issue by rhlarora84** [localstack/awscli-local#40]
Localstack is already installed.

![image](https://user-images.githubusercontent.com/15618263/111378743-a2c5c680-8678-11eb-96e8-fe7d2915a55d.png)

**Comment by Juanka7** [comment]
In the requirements https://github.com/localstack/awscli-local/blob/master/requirements.txt is that requirement. if pip dont install the requirement the link is what you need install https://github.com/localstack/localstack-python-client

**Comment by whummer** [comment]
Thanks for reporting @rhlarora84 , and thanks for providing a solution @Juanka7 👍 . Should be relatively straight-forward to resolve. Please let us know if there are any other issues. Thanks
