### ISSUE TITLE
Cannot install v1

### ISSUE THREAD

**Issue by paul-uz** [localstack/awscli-local#42]
I am trying to run the command form the README

`pip3 install awscli-local[ver1]` (using python 3, hence pip3)

but get

`zsh: no matches found: awscli-local[ver1]`

EDIT - I originally has AWS CLI v 2 installed, but used heombrew to install and link AWS CLI v1. But, I stiol cannot install `awscli-local[v1]`

**Comment by whummer** [comment]
Thanks for reporting @paul-uz . There are currently some limitations with v2 - we have updated our documentation (and a possible workaround) here: https://github.com/localstack/awscli-local#limitations 

Generally, we recommend installing `awslocal` with the AWS CLI v1. 

Please let us know if the problem persists. Thanks!

**Comment by thomas-humi** [comment]
For anyone who has this use, @paul-uz is using zsh, not bash.

This should work:
```
pip3 install 'awscli-local[ver1]'
```

Note the single quotes. zsh was treating the square brackets as special characters.
I ran into this to.

**Comment by nmquaan** [comment]
It worked for me. Thanks, @thomas-humi

**Comment by Exrelativity** [comment]
solution to this
```
 pip install 'awscli-local[ver1]'
```
