### ISSUE TITLE
missing awscli

### ISSUE THREAD

**Issue by nhomble** [localstack/awscli-local#43]
In a fresh virtual environment, I did
```bash
$ pip install awscli-local
$ awslocal
```
which produced the following error: `ModuleNotFoundError: No module named 'awscli'`

This was fixable by just doing
```bash
$ pip install awscli
$ awslocal --version
aws-cli/1.19.39 Python/3.9.2 Windows/10 botocore/1.20.39
```

shouldn't we tell pip the dependency when installing `awslocal` in the first place? 

*NOTE*
I did try on different versions of pip since the changelog mentioned new args for new pip versions
```bash
$ pip --version
pip 20.2.3 
```
```bash
$ pip --version
pip 21.0.1 
```

**Comment by nhomble** [comment]
any reason we are doing `extras_require`?  https://github.com/localstack/awscli-local/blob/master/setup.py#L20

**Comment by whummer** [comment]
Thanks for reporting @nhomble . The assumption is that `aws` is already pre-installed, as `awslocal` is supposed to work with both - v1 and v2 of the AWS CLI.

We recommend installing `awscli-local[ver1]` - the current limitations with v2 are documented here: https://github.com/localstack/awscli-local#limitations

Hope that helps - please keep us posted if there are any other issues. Thanks!
