### ISSUE TITLE
Please allow us to change the localstack port

### ISSUE THREAD

**Issue by ryboe** [localstack/awscli-local#57]
```sh
$ LOCALSTACK_HOST='localhost:4599' awslocal s3 ls                                                                                          0

Port could not be cast to integer value as '4599:4566'
```

**Comment by whummer** [comment]
Thanks for reporting @ryboe - can you try using the `EDGE_PORT` config variable, which allows you to customize the target port:

```
$ EDGE_PORT='4599' awslocal s3 ls 
...
```

We have added a short note to the Configuration section of the README: https://github.com/localstack/awscli-local#configurations . Please let us know if there are any other questions or issues.. Thanks!
