### ISSUE TITLE
s3api not automatic wrap localstack endpoint

### ISSUE THREAD

**Issue by ghost** [localstack/awscli-local#58]
If you are using awslocal s3api to create bucket its not wrapping the endpoint for LocalStack you need to add the endpoint self.

``` bash
awslocal s3api create-bucket \
    --bucket {bucket-name} \
    --endpoint-url=http://localhost:4566
```

Shoud be a option to do, whitout defineding the endpoint.
```
awslocal s3api create-bucket \
    --bucket {bucket-name}
```

**Comment by whummer** [comment]
Thanks for reporting @ParisNakitaKejser-EB . This should be working in the meantime:

```
$ awslocal s3api create-bucket --bucket test123
{
    "Location": "/test123"
}
```

Can you please pull the latest Docker image (`docker pull localstack/localstack`) and install the latest version of the `awslocal` command line. Please keep us posted on how it goes.. Thanks!

**Comment by bentsku** [comment]
I'll close the issue as there has been no response since a year. This should be fixed! Thanks for the report
