### ISSUE TITLE
Please pass HOME env variable.

### ISSUE THREAD

**Issue by ma2yama** [localstack/awscli-local#59]
I tried to use `awslocal` with aws-cli installed by [asdf](https://asdf-vm.com/) but could not.

The reason is that `asdf` uses  `HOME` env variable.
https://github.com/asdf-vm/asdf/blob/b7dd291c983af321af20550fa89bf1cfbc888aec/asdf.sh#L26

Please pass `HOME` env variable.

**Comment by whummer** [comment]
Hi @ma2yama , thanks for reporting. Do you think you could create a small pull request with this change? Happy to get it merged and released..! Thanks

**Comment by ma2yama** [comment]
I made a pull request #63, so please check.

**Comment by whummer** [comment]
Fixed via #63
