### ISSUE TITLE
Cannot get a live stream of logs using awslocal logs tail --follow 

### ISSUE THREAD

**Issue by crushingCodes** [localstack/awscli-local#65]
Im just getting used to using localstack, thanks for the project by the way it's very cool, and this wrapper makes it easier to interact with it.

But just noticed it wasn't possible to get a live stream of logs using the following:
`awslocal logs tail --follow /aws/lambda/example_lambda`
This only prints out the logs once I stop the command.

As a workaround I found a way to use the aws cli with the following:
`aws --endpoint-url=http://localhost:4566 --no-verify-ssl logs tail /aws/lambda/example_lambda --follow`
This will print logs out live as I trigger the function to run.

To easily reproduce this, make a lambda
In terminal 1 run 
`awslocal logs tail --follow /aws/lambda/example_lambda`

In terminal 2 run:
`awslocal lambda invoke --function-name example_lambda --cli-binary-format raw-in-base64-out --payload '{"key1": "value1"}' outputfile.txt`

notice no logs showing, if you cancel the command, it will then show the output.

Not a big deal since there is a workaround, but maybe it would be good if the awslocal cli supported this, cheers.

**Comment by jweyrich** [comment]
it seems that the package is missing a  Python dependency: awscli
Probably should adopt awscliv2 though.

**Comment by dfangl** [comment]
This behavior should be fixed with #78 and is released in version 0.21. Thank you for reporting this issue!
