### ISSUE TITLE
Error when using 'awslocal configure list'

### ISSUE THREAD

**Issue by yo-ga** [localstack/awscli-local#66]
Environment:
- awscli-local: 0.20 (from awscli_local-0.20-py3-none-any.whl)
- localstack: 1.2.0
- aws-cli/2.8.12 Python/3.10.8 Darwin/22.1.0 source/x86_64 prompt/off

When I used `awslocal configure list`, I got `ERROR: Unable to find LocalStack endpoint for service "configure"`.
It should be used to verify the current configuration as the [document](https://docs.localstack.cloud/integrations/aws-cli/#configurations) said.

**Comment by uzaxirr** [comment]
I can reproduce it as well
<img width="814" alt="Screenshot 2022-11-28 at 1 37 32 AM" src="https://user-images.githubusercontent.com/72073401/204157241-0f40b076-63c2-444c-ae96-584670802ccf.png">

**Comment by eduardocarrerah** [comment]
same thing 
<img width="851" alt="Screen Shot 2023-02-25 at 11 29 03 AM" src="https://user-images.githubusercontent.com/119906405/221371018-c0e9ee07-e3ab-4ce8-9e10-b5ed3a7a2c8f.png">

**Comment by solodezaldivar** [comment]
Any update on this?

**Comment by aarbanas** [comment]
I am having a same issue. Any feedback on this error?
![image](https://github.com/localstack/awscli-local/assets/26416707/4e9bda85-5559-4d69-8a19-6ec00136b317)
