### ISSUE TITLE
awslocal with LOCALSTACK_HOST - Invalid endpoint

### ISSUE THREAD

**Issue by black-snow** [localstack/awscli-local#67]
I'm trying to invoke stuff in my localstack container (named `localstack_main`) from another localstack container (`docker run --rm -it --network=container:localstack_main --entrypoint="" -e LOCALSTACK_HOST=localstack_main localstack/localstack awslocal sns create-topic --name test` - or `--network=network-name`), but this results in:

> Invalid endpoint: http://localstack_main:4566

But the port is reachable from within the auxilliary container:
```
root@fc8d9a10f8c9:/opt/code/localstack# nmap -p4000-5000 localstack_main
Starting Nmap 7.70 ( https://nmap.org ) at 2022-11-28 11:08 UTC
Nmap scan report for localstack_main (172.27.0.3)
Host is up (0.0000040s latency).
rDNS record for 172.27.0.3: fc8d9a10f8c9
Not shown: 938 closed ports, 62 filtered ports
PORT     STATE SERVICE
4566/tcp open  kwtc
```

And `awslocal sns create-topic --name test` works fine from within the `localstack_main` container.

Am I missing something?

**Comment by black-snow** [comment]
`curl -v 'http://localstack_main:4566?Action=CreateTopic&Name=test&Version=2010-03-31'` also sucessfully creates the topic from within the aux container.

**Comment by black-snow** [comment]
`aws sns --endpoint-url http://localhost:4566 create-topic --name test --region=us-east-1` works fine as well when I mount my cradentials

**Comment by black-snow** [comment]
Same issue with `aws sns --endpoint-url http://localstack_main:4566 create-topic --name test --region=us-east-1` ... mhm

**Comment by bentsku** [comment]
Hello @black-snow and thanks for your report. It might be because the `_` character is not legal in hostnames. Could you try renaming your container to `localstack-main` and give it a new try? Thanks!

**Comment by black-snow** [comment]
@bentsku valid point! Thanks!
