### ISSUE TITLE
awslocal kinesis list-streams fails when USE_SSL is true 

### ISSUE THREAD

**Issue by justinborromeo-toast** [localstack/awscli-local#7]
I installed localstack using `pip install localstack` and am running it using `USE_SSL=true localstack --start docker`.  When USE_SSL is true, running `awslocal kinesis list-streams` fails with the message " Connection was closed before we received a valid response from endpoint URL: "http://localhost:4568/"."

**Comment by jordanboston** [comment]
On this note, I am wondering where we can set the configuration for the ENV VAR for USE_SSL=true?

Would not want to type that in `USE_SSL=true awslocal ..` everytime if possible.

**Comment by whummer** [comment]
> On this note, I am wondering where we can set the configuration for the ENV VAR for USE_SSL=true?


@jordanboston you can set this configuration permanently in your terminal like so:
```
export USE_SSL=true
```
You can also add this line to your `.bash_profile` and/or `.profile` to load it automatically for each session.

**Comment by whummer** [comment]
@justinborromeo-toast This is a pretty old issues, but let me try to give an answer. You should set `USE_SSL=true` for both - the LocalStack server process, and the `awslocal` client process. Hope that helps.
