### ISSUE TITLE
Awslocal cli: Exception while calling ecs.CreateCluster: 'EcrStore' object has no attribute 'clusters'

### ISSUE THREAD

**Issue by solodezaldivar** [localstack/awscli-local#72]
On windows, I'm trying to execute `awslocal ecs create-cluster --cluster-name clusterName` but it fails with this error message
![image](https://github.com/localstack/awscli-local/assets/55449626/ca9b3028-b009-4816-9b90-1703590937e8)

I've installed both aws cli and awslocal cli. Any ideas?

**Comment by alexrashed** [comment]
Hi @solodezaldivar!
It actually seems like `awslocal` is working just fine, but LocalStack is reporting an error to your `create-cluster` request.
I cannot reproduce your issue with the latest Docker image. If you are still facing your issue after updating to the latest version of the Docker image, please create an issue with detailed information about the LocalStack version you are using in the [localstack/localstack](https://github.com/localstack/localstack/issues) repository.
Thanks!
