### ISSUE TITLE
Not using pager.

### ISSUE THREAD

**Issue by markeganfuller** [localstack/awscli-local#74]
`awslocal` doesn't use a pager for the `help` subcommand whereas `aws` does.

Example:
```
awslocal ec2 describe-vpcs help
aws ec2 describe-vpcs help
```

`awslocal` will just echo the page, whereas `aws` will use a pager. I assume this is likely due to `awslocal` wrapping `aws` and causing it to think its being used by another program and disabling the pager.

This may be[ fixable with some environment variables](https://github.com/aws/aws-cli/pull/4702#issue-344978525) but I haven't tested it.

**Comment by dfangl** [comment]
The changes have been released as version 0.21.
