### ISSUE TITLE
awslocal sqs list-queues command returns unknown output type: dotnet -v

### ISSUE THREAD

**Issue by patelneel1994** [localstack/awscli-local#8]
When I run `awslocal sqs list-queues` in my OSx Terminal I get Unknown output type: dotnet -v  output. 
LAP1923TN:~ user$ awslocal sqs list-queues

Unknown output type: dotnet -v

**Comment by whummer** [comment]
Thanks for reporting @patelneel1994 . I wasn't able to reproduce this issue, this is what I'm seeing:
```
$ awslocal sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4576/queue/q1"
    ]
}
```

Can you please provide some details about your environment - version of python, pip, etc
```
pip --version
python --version
/usr/bin/env python --version
```
