### ISSUE TITLE
Why not use this? alias awslocal='aws --endpoint-url=http://localhost:4566'

### ISSUE THREAD

**Issue by creotiv** [localstack/awscli-local#82]
What difference awslocal has to aws ?

**Comment by alexrashed** [comment]
Well, that's a good question! As mentioned in the [readme](https://github.com/localstack/awscli-local?tab=readme-ov-file#example), this is pretty much the same command.
However, it can be handy to have this config by just switching the command (maybe even with an `alias` switching between prod and local dev). And in addition to the endpoint URL config, `awslocal` also performs some other optimizations concerning the endpoint and TLS handling.
But yes, this 270 LoC script is all there is to `awslocal`: https://github.com/localstack/awscli-local/blob/master/bin/awslocal
Which in my opinion shows quite well how good LocalStack is as a drop-in replacement of live AWS services... 😄
